//
// Created by Ghost on 2023/8/25.
//
/* DO NOT EDIT THIS FILE - it is automatically generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_example_BarcodeGenerator */

#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGF(...) __android_log_print(ANDROID_LOG_FATAL, LOG_TAG, __VA_ARGS__)

#ifndef PRINTER_AS_COM_BARCODE_H
#define PRINTER_AS_COM_BARCODE_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef LOG_TAG
#define LOG_TAG "BarcodeGeneratorJNI"
#endif

/*
 * Class:     com_example_BarcodeGenerator
 * Method:    generateBarcode
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jobject JNICALL Java_com_industry_printer_data_BarcodeGeneratorJNI_generateBarcode(JNIEnv *, jclass, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif //PRINTER_AS_COM_BARCODE_H
